/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Content;

/**
 *
 * @author Administrator
 */
public class SecondPanel extends javax.swing.JPanel {

    /**
     * Creates new form SecondPanel
     */
    public SecondPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(102, 102, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Available Rooms");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 369, -1));

        jTable1.setForeground(new java.awt.Color(255, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"000", "01", "Double Suite", "Available"},
                {"001", "01", "Single Suite	Single Suite", "Unavailable"},
                {"002", "02", "Deluxe Suite", "Available"},
                {"003", "02", "Single Suite", "Available"},
                {"004", "02", "King Suite", "Available"},
                {"005", "02", "Deluxe Suite", "Unavaiable"},
                {"006", "03", "King Suite", "Available"},
                {"007", "03", "Single Suite", "Unavaiable"},
                {"008", "03", "Deluxe Suite", "Available"},
                {"009", "03", "Single Suite", "Available"},
                {"010", "03", "Deluxe Suite", "Unavaiable"},
                {"011", "05", "Double Suite", "Available"},
                {"012", "05", "Double Suite", "Available"},
                {"013", "05", "Double Suite", "Available"},
                {"014", "05", "King Suite", "Unavaiable"},
                {"015", "05", "Deluxe Suite", "Unavaiable"},
                {"016", "05", "Single Suite", "Available"},
                {"017", "06", "Deluxe Suite", "Unavaiable"},
                {"018", "06", "Deluxe Suite", "Available"},
                {"019", "06", "Deluxe Suite", "Available"},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Room Number", "Floor Number", "Room Type", "Availability"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 760, 460));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
